log_dir: "Checkpoint"
save_freq: 10
device: "cuda"
epochs: 100
batch_size: 64
pretrained_model: ""
train_data: "Data/train_list.txt"
val_data: "Data/val_list.txt"
num_workers: 16

  
optimizer_params:
  lr: 0.0003
  
loss_params:
  lambda_f0: 0.1

dataset_params:
  mel_params:
    sample_rate: 24000
    win_len: 1024
    n_fft: 1024
    n_mels: 80
    hop_length: 300
  
